#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 156
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_COLON = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_function = 6,
  anon_sym_class = 7,
  anon_sym_public = 8,
  anon_sym_private = 9,
  anon_sym_protected = 10,
  anon_sym_static = 11,
  anon_sym_final = 12,
  anon_sym_abstract = 13,
  anon_sym_synchronized = 14,
  anon_sym_LPAREN = 15,
  anon_sym_COMMA = 16,
  anon_sym_RPAREN = 17,
  anon_sym_LBRACE = 18,
  anon_sym_RBRACE = 19,
  anon_sym_int = 20,
  anon_sym_float = 21,
  anon_sym_string = 22,
  anon_sym_boolean = 23,
  anon_sym_PIPE_PIPE = 24,
  anon_sym_AMP_AMP = 25,
  sym_number = 26,
  sym_string = 27,
  sym_line_comment = 28,
  sym_block_comment = 29,
  anon_sym_extends = 30,
  anon_sym_implements = 31,
  sym_program = 32,
  sym__toplevel_statement = 33,
  sym_statement = 34,
  sym_variable_declaration = 35,
  sym_method_declaration = 36,
  sym_class_declaration = 37,
  sym_modifiers = 38,
  sym_parameters = 39,
  sym_parameter = 40,
  sym_return_type = 41,
  sym_class_body = 42,
  sym_field_declaration = 43,
  sym_type = 44,
  sym_expression_statement = 45,
  sym_expression = 46,
  sym_assignment_expression = 47,
  sym_binary_expression = 48,
  sym_primary_expression = 49,
  sym_extends_clause = 50,
  sym_implements_clause = 51,
  sym_block = 52,
  sym__statement = 53,
  aux_sym_program_repeat1 = 54,
  aux_sym_modifiers_repeat1 = 55,
  aux_sym_parameters_repeat1 = 56,
  aux_sym_class_body_repeat1 = 57,
  aux_sym_implements_clause_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_function] = "function",
  [anon_sym_class] = "class",
  [anon_sym_public] = "public",
  [anon_sym_private] = "private",
  [anon_sym_protected] = "protected",
  [anon_sym_static] = "static",
  [anon_sym_final] = "final",
  [anon_sym_abstract] = "abstract",
  [anon_sym_synchronized] = "synchronized",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_string] = "string",
  [anon_sym_boolean] = "boolean",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [anon_sym_extends] = "extends",
  [anon_sym_implements] = "implements",
  [sym_program] = "program",
  [sym__toplevel_statement] = "_toplevel_statement",
  [sym_statement] = "statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_method_declaration] = "method_declaration",
  [sym_class_declaration] = "class_declaration",
  [sym_modifiers] = "modifiers",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_return_type] = "return_type",
  [sym_class_body] = "class_body",
  [sym_field_declaration] = "field_declaration",
  [sym_type] = "type",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_extends_clause] = "extends_clause",
  [sym_implements_clause] = "implements_clause",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_modifiers_repeat1] = "modifiers_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_class_body_repeat1] = "class_body_repeat1",
  [aux_sym_implements_clause_repeat1] = "implements_clause_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_protected] = anon_sym_protected,
  [anon_sym_static] = anon_sym_static,
  [anon_sym_final] = anon_sym_final,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_synchronized] = anon_sym_synchronized,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_implements] = anon_sym_implements,
  [sym_program] = sym_program,
  [sym__toplevel_statement] = sym__toplevel_statement,
  [sym_statement] = sym_statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_method_declaration] = sym_method_declaration,
  [sym_class_declaration] = sym_class_declaration,
  [sym_modifiers] = sym_modifiers,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_return_type] = sym_return_type,
  [sym_class_body] = sym_class_body,
  [sym_field_declaration] = sym_field_declaration,
  [sym_type] = sym_type,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_extends_clause] = sym_extends_clause,
  [sym_implements_clause] = sym_implements_clause,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_modifiers_repeat1] = aux_sym_modifiers_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_class_body_repeat1] = aux_sym_class_body_repeat1,
  [aux_sym_implements_clause_repeat1] = aux_sym_implements_clause_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protected] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_static] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_final] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_synchronized] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_implements] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_method_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_class_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_modifiers] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym_class_body] = {
    .visible = true,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_extends_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_implements_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_modifiers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_implements_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 12,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 13,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 26,
  [37] = 37,
  [38] = 21,
  [39] = 39,
  [40] = 29,
  [41] = 41,
  [42] = 34,
  [43] = 37,
  [44] = 17,
  [45] = 23,
  [46] = 41,
  [47] = 18,
  [48] = 28,
  [49] = 31,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 51,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 54,
  [64] = 57,
  [65] = 60,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 68,
  [75] = 70,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 76,
  [81] = 79,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 84,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 98,
  [102] = 89,
  [103] = 103,
  [104] = 86,
  [105] = 87,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 120,
  [124] = 124,
  [125] = 124,
  [126] = 122,
  [127] = 127,
  [128] = 121,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 118,
  [133] = 130,
  [134] = 113,
  [135] = 131,
  [136] = 136,
  [137] = 129,
  [138] = 138,
  [139] = 127,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 142,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 148,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 140,
  [155] = 152,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 1,
        '&', 2,
        '(', 11,
        ')', 13,
        ',', 12,
        '/', 3,
        ':', 8,
        ';', 10,
        '=', 9,
        '{', 14,
        '|', 6,
        '}', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '|') ADVANCE(16);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'e', 4,
        'f', 5,
        'i', 6,
        'p', 7,
        's', 8,
        'v', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'b') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'm') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(21);
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 33:
      if (lookahead == 'v') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'c') ADVANCE(53);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'h') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 55:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_final);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 61:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 63:
      if (lookahead == 'c') ADVANCE(74);
      END_STATE();
    case 64:
      if (lookahead == 'c') ADVANCE(75);
      END_STATE();
    case 65:
      if (lookahead == 'c') ADVANCE(76);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(77);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 68:
      if (lookahead == 'c') ADVANCE(79);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 70:
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(82);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_static);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 78:
      if (lookahead == 'o') ADVANCE(86);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 83:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 90:
      if (lookahead == 'd') ADVANCE(93);
      END_STATE();
    case 91:
      if (lookahead == 'i') ADVANCE(94);
      END_STATE();
    case 92:
      if (lookahead == 's') ADVANCE(95);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_protected);
      END_STATE();
    case 94:
      if (lookahead == 'z') ADVANCE(96);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_implements);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 97:
      if (lookahead == 'd') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_synchronized);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_protected] = ACTIONS(1),
    [anon_sym_static] = ACTIONS(1),
    [anon_sym_final] = ACTIONS(1),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_synchronized] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_implements] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(147),
    [sym__toplevel_statement] = STATE(2),
    [sym_statement] = STATE(2),
    [sym_variable_declaration] = STATE(37),
    [sym_method_declaration] = STATE(2),
    [sym_class_declaration] = STATE(2),
    [sym_modifiers] = STATE(97),
    [sym_expression_statement] = STATE(37),
    [sym_expression] = STATE(98),
    [sym_assignment_expression] = STATE(103),
    [sym_binary_expression] = STATE(103),
    [sym_primary_expression] = STATE(103),
    [aux_sym_program_repeat1] = STATE(2),
    [aux_sym_modifiers_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_function] = ACTIONS(11),
    [anon_sym_class] = ACTIONS(13),
    [anon_sym_public] = ACTIONS(15),
    [anon_sym_private] = ACTIONS(15),
    [anon_sym_protected] = ACTIONS(15),
    [anon_sym_static] = ACTIONS(15),
    [anon_sym_final] = ACTIONS(15),
    [anon_sym_abstract] = ACTIONS(15),
    [anon_sym_synchronized] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_var,
    ACTIONS(11), 1,
      anon_sym_function,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(97), 1,
      sym_modifiers,
    STATE(98), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(37), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(3), 5,
      sym__toplevel_statement,
      sym_statement,
      sym_method_declaration,
      sym_class_declaration,
      aux_sym_program_repeat1,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [58] = 14,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(26), 1,
      anon_sym_var,
    ACTIONS(29), 1,
      anon_sym_function,
    ACTIONS(32), 1,
      anon_sym_class,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(97), 1,
      sym_modifiers,
    STATE(98), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(38), 2,
      sym_number,
      sym_string,
    STATE(37), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(3), 5,
      sym__toplevel_statement,
      sym_statement,
      sym_method_declaration,
      sym_class_declaration,
      aux_sym_program_repeat1,
    ACTIONS(35), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [116] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_var,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(101), 1,
      sym_expression,
    STATE(144), 1,
      sym_modifiers,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(43), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(6), 4,
      sym_statement,
      sym_block,
      sym__statement,
      aux_sym_block_repeat1,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [170] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_var,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(101), 1,
      sym_expression,
    STATE(144), 1,
      sym_modifiers,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(43), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(7), 4,
      sym_statement,
      sym_block,
      sym__statement,
      aux_sym_block_repeat1,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [224] = 13,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_var,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(101), 1,
      sym_expression,
    STATE(144), 1,
      sym_modifiers,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(43), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(6), 4,
      sym_statement,
      sym_block,
      sym__statement,
      aux_sym_block_repeat1,
    ACTIONS(55), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [278] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_var,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(101), 1,
      sym_expression,
    STATE(144), 1,
      sym_modifiers,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(43), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(6), 4,
      sym_statement,
      sym_block,
      sym__statement,
      aux_sym_block_repeat1,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [332] = 13,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_var,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(101), 1,
      sym_expression,
    STATE(144), 1,
      sym_modifiers,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(43), 2,
      sym_variable_declaration,
      sym_expression_statement,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(4), 4,
      sym_statement,
      sym_block,
      sym__statement,
      aux_sym_block_repeat1,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [386] = 9,
    ACTIONS(72), 1,
      anon_sym_function,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(56), 1,
      sym_modifiers,
    STATE(151), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(11), 3,
      sym_method_declaration,
      sym_field_declaration,
      aux_sym_class_body_repeat1,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [427] = 9,
    ACTIONS(79), 1,
      anon_sym_function,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(56), 1,
      sym_modifiers,
    STATE(151), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(10), 3,
      sym_method_declaration,
      sym_field_declaration,
      aux_sym_class_body_repeat1,
    ACTIONS(76), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
    ACTIONS(82), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [468] = 9,
    ACTIONS(72), 1,
      anon_sym_function,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_modifiers_repeat1,
    STATE(56), 1,
      sym_modifiers,
    STATE(151), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(10), 3,
      sym_method_declaration,
      sym_field_declaration,
      aux_sym_class_body_repeat1,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
    ACTIONS(15), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
  [509] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(91), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(89), 14,
      anon_sym_var,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [536] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(95), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(93), 14,
      anon_sym_var,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [563] = 4,
    STATE(15), 1,
      aux_sym_modifiers_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(99), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
    ACTIONS(97), 8,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [590] = 4,
    STATE(15), 1,
      aux_sym_modifiers_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(103), 7,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
    ACTIONS(101), 8,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [617] = 3,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(106), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [640] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(112), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [663] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(116), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [686] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(89), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [709] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(120), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [732] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(122), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(124), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [755] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(128), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [778] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(132), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [801] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(136), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [824] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(93), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [847] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(138), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(140), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [870] = 3,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(142), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [893] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(148), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [916] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(152), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [939] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(156), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [962] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(160), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [985] = 3,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(162), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1008] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(168), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1031] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(170), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(172), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1054] = 3,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(174), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1077] = 3,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1100] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(178), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(180), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1123] = 3,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(124), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1146] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(182), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(184), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1169] = 3,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(152), 13,
      anon_sym_function,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1192] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(186), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(188), 11,
      anon_sym_var,
      anon_sym_function,
      anon_sym_class,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1215] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(170), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(172), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1237] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(178), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(180), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1259] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(110), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(112), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1281] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(132), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1303] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(186), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(188), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1325] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(114), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(116), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1347] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(146), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(148), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1369] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(158), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(160), 9,
      anon_sym_var,
      anon_sym_public,
      anon_sym_private,
      anon_sym_protected,
      anon_sym_static,
      anon_sym_final,
      anon_sym_abstract,
      anon_sym_synchronized,
      sym_identifier,
  [1391] = 5,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_parameter,
    STATE(143), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1412] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(84), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1432] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(93), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1452] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(107), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1472] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(89), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1492] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(94), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1512] = 4,
    ACTIONS(194), 1,
      anon_sym_function,
    STATE(146), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1530] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(86), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1550] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(95), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1570] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(99), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1590] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(87), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1610] = 4,
    STATE(111), 1,
      sym_parameter,
    STATE(143), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1628] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(106), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1648] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(102), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1668] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(104), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1688] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(105), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    STATE(103), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1708] = 3,
    STATE(110), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1723] = 3,
    STATE(114), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1738] = 3,
    STATE(142), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1753] = 7,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 1,
      anon_sym_extends,
    ACTIONS(200), 1,
      anon_sym_implements,
    STATE(39), 1,
      sym_class_body,
    STATE(82), 1,
      sym_extends_clause,
    STATE(112), 1,
      sym_implements_clause,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1776] = 3,
    STATE(149), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1791] = 7,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 1,
      anon_sym_extends,
    ACTIONS(200), 1,
      anon_sym_implements,
    STATE(20), 1,
      sym_class_body,
    STATE(78), 1,
      sym_extends_clause,
    STATE(115), 1,
      sym_implements_clause,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1814] = 3,
    STATE(153), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1829] = 3,
    STATE(96), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1844] = 3,
    STATE(145), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1859] = 3,
    STATE(148), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(70), 5,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      sym_identifier,
  [1874] = 5,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(202), 1,
      anon_sym_COLON,
    STATE(36), 1,
      sym_block,
    STATE(125), 1,
      sym_return_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1891] = 3,
    ACTIONS(204), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(206), 3,
      anon_sym_SEMI,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1904] = 5,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_implements,
    STATE(39), 1,
      sym_class_body,
    STATE(112), 1,
      sym_implements_clause,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1921] = 5,
    ACTIONS(202), 1,
      anon_sym_COLON,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
    STATE(137), 1,
      sym_return_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1938] = 5,
    ACTIONS(202), 1,
      anon_sym_COLON,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_block,
    STATE(124), 1,
      sym_return_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1955] = 5,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(202), 1,
      anon_sym_COLON,
    STATE(38), 1,
      sym_block,
    STATE(129), 1,
      sym_return_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1972] = 5,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_implements,
    STATE(24), 1,
      sym_class_body,
    STATE(108), 1,
      sym_implements_clause,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1989] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(210), 2,
      sym_identifier,
      anon_sym_implements,
    ACTIONS(212), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [2002] = 4,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2016] = 4,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_LBRACE,
    STATE(91), 1,
      aux_sym_implements_clause_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2030] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(224), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2044] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(226), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2058] = 4,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2072] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2086] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(100), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2100] = 4,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    STATE(91), 1,
      aux_sym_implements_clause_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2114] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(206), 3,
      anon_sym_SEMI,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [2124] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2138] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(246), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2152] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(248), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2166] = 4,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      aux_sym_implements_clause_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2180] = 4,
    ACTIONS(252), 1,
      anon_sym_var,
    ACTIONS(254), 1,
      anon_sym_function,
    ACTIONS(256), 1,
      anon_sym_class,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2194] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(258), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2208] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(260), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2222] = 4,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2236] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(264), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2250] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2264] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(268), 3,
      anon_sym_SEMI,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [2274] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(270), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2288] = 4,
    ACTIONS(216), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(272), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2302] = 3,
    ACTIONS(218), 1,
      anon_sym_AMP_AMP,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(274), 2,
      anon_sym_SEMI,
      anon_sym_PIPE_PIPE,
  [2314] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(274), 3,
      anon_sym_SEMI,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [2324] = 3,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_class_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2335] = 3,
    ACTIONS(276), 1,
      anon_sym_EQ,
    ACTIONS(278), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2346] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(280), 2,
      anon_sym_LBRACE,
      anon_sym_implements,
  [2355] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(231), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2364] = 3,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_class_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2375] = 3,
    ACTIONS(282), 1,
      sym_identifier,
    ACTIONS(284), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2386] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(242), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [2395] = 3,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_class_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2406] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(286), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [2415] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(288), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [2424] = 3,
    ACTIONS(290), 1,
      sym_identifier,
    ACTIONS(292), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2435] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(294), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2444] = 3,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    ACTIONS(296), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2455] = 3,
    ACTIONS(298), 1,
      anon_sym_EQ,
    ACTIONS(300), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2466] = 3,
    ACTIONS(302), 1,
      anon_sym_EQ,
    ACTIONS(304), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2477] = 3,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    ACTIONS(306), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2488] = 3,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2499] = 3,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2510] = 3,
    ACTIONS(308), 1,
      anon_sym_EQ,
    ACTIONS(310), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2521] = 3,
    ACTIONS(270), 1,
      anon_sym_SEMI,
    ACTIONS(312), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2532] = 3,
    ACTIONS(314), 1,
      anon_sym_EQ,
    ACTIONS(316), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2543] = 3,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2554] = 3,
    ACTIONS(318), 1,
      anon_sym_LPAREN,
    STATE(80), 1,
      sym_parameters,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2565] = 3,
    ACTIONS(318), 1,
      anon_sym_LPAREN,
    STATE(79), 1,
      sym_parameters,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2576] = 3,
    ACTIONS(320), 1,
      sym_identifier,
    ACTIONS(322), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2587] = 3,
    ACTIONS(318), 1,
      anon_sym_LPAREN,
    STATE(76), 1,
      sym_parameters,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2598] = 3,
    ACTIONS(324), 1,
      sym_identifier,
    ACTIONS(326), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2609] = 3,
    ACTIONS(318), 1,
      anon_sym_LPAREN,
    STATE(81), 1,
      sym_parameters,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2620] = 3,
    ACTIONS(328), 1,
      anon_sym_EQ,
    ACTIONS(330), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2631] = 3,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2642] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(332), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [2651] = 3,
    ACTIONS(224), 1,
      anon_sym_SEMI,
    ACTIONS(334), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2662] = 2,
    ACTIONS(336), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2670] = 2,
    ACTIONS(338), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2678] = 2,
    ACTIONS(340), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2686] = 2,
    ACTIONS(342), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2694] = 2,
    ACTIONS(344), 1,
      anon_sym_var,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2702] = 2,
    ACTIONS(346), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2710] = 2,
    ACTIONS(348), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2718] = 2,
    ACTIONS(350), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2726] = 2,
    ACTIONS(352), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2734] = 2,
    ACTIONS(354), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2742] = 2,
    ACTIONS(356), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2750] = 2,
    ACTIONS(358), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2758] = 2,
    ACTIONS(360), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2766] = 2,
    ACTIONS(362), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2774] = 2,
    ACTIONS(364), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2782] = 2,
    ACTIONS(366), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 116,
  [SMALL_STATE(5)] = 170,
  [SMALL_STATE(6)] = 224,
  [SMALL_STATE(7)] = 278,
  [SMALL_STATE(8)] = 332,
  [SMALL_STATE(9)] = 386,
  [SMALL_STATE(10)] = 427,
  [SMALL_STATE(11)] = 468,
  [SMALL_STATE(12)] = 509,
  [SMALL_STATE(13)] = 536,
  [SMALL_STATE(14)] = 563,
  [SMALL_STATE(15)] = 590,
  [SMALL_STATE(16)] = 617,
  [SMALL_STATE(17)] = 640,
  [SMALL_STATE(18)] = 663,
  [SMALL_STATE(19)] = 686,
  [SMALL_STATE(20)] = 709,
  [SMALL_STATE(21)] = 732,
  [SMALL_STATE(22)] = 755,
  [SMALL_STATE(23)] = 778,
  [SMALL_STATE(24)] = 801,
  [SMALL_STATE(25)] = 824,
  [SMALL_STATE(26)] = 847,
  [SMALL_STATE(27)] = 870,
  [SMALL_STATE(28)] = 893,
  [SMALL_STATE(29)] = 916,
  [SMALL_STATE(30)] = 939,
  [SMALL_STATE(31)] = 962,
  [SMALL_STATE(32)] = 985,
  [SMALL_STATE(33)] = 1008,
  [SMALL_STATE(34)] = 1031,
  [SMALL_STATE(35)] = 1054,
  [SMALL_STATE(36)] = 1077,
  [SMALL_STATE(37)] = 1100,
  [SMALL_STATE(38)] = 1123,
  [SMALL_STATE(39)] = 1146,
  [SMALL_STATE(40)] = 1169,
  [SMALL_STATE(41)] = 1192,
  [SMALL_STATE(42)] = 1215,
  [SMALL_STATE(43)] = 1237,
  [SMALL_STATE(44)] = 1259,
  [SMALL_STATE(45)] = 1281,
  [SMALL_STATE(46)] = 1303,
  [SMALL_STATE(47)] = 1325,
  [SMALL_STATE(48)] = 1347,
  [SMALL_STATE(49)] = 1369,
  [SMALL_STATE(50)] = 1391,
  [SMALL_STATE(51)] = 1412,
  [SMALL_STATE(52)] = 1432,
  [SMALL_STATE(53)] = 1452,
  [SMALL_STATE(54)] = 1472,
  [SMALL_STATE(55)] = 1492,
  [SMALL_STATE(56)] = 1512,
  [SMALL_STATE(57)] = 1530,
  [SMALL_STATE(58)] = 1550,
  [SMALL_STATE(59)] = 1570,
  [SMALL_STATE(60)] = 1590,
  [SMALL_STATE(61)] = 1610,
  [SMALL_STATE(62)] = 1628,
  [SMALL_STATE(63)] = 1648,
  [SMALL_STATE(64)] = 1668,
  [SMALL_STATE(65)] = 1688,
  [SMALL_STATE(66)] = 1708,
  [SMALL_STATE(67)] = 1723,
  [SMALL_STATE(68)] = 1738,
  [SMALL_STATE(69)] = 1753,
  [SMALL_STATE(70)] = 1776,
  [SMALL_STATE(71)] = 1791,
  [SMALL_STATE(72)] = 1814,
  [SMALL_STATE(73)] = 1829,
  [SMALL_STATE(74)] = 1844,
  [SMALL_STATE(75)] = 1859,
  [SMALL_STATE(76)] = 1874,
  [SMALL_STATE(77)] = 1891,
  [SMALL_STATE(78)] = 1904,
  [SMALL_STATE(79)] = 1921,
  [SMALL_STATE(80)] = 1938,
  [SMALL_STATE(81)] = 1955,
  [SMALL_STATE(82)] = 1972,
  [SMALL_STATE(83)] = 1989,
  [SMALL_STATE(84)] = 2002,
  [SMALL_STATE(85)] = 2016,
  [SMALL_STATE(86)] = 2030,
  [SMALL_STATE(87)] = 2044,
  [SMALL_STATE(88)] = 2058,
  [SMALL_STATE(89)] = 2072,
  [SMALL_STATE(90)] = 2086,
  [SMALL_STATE(91)] = 2100,
  [SMALL_STATE(92)] = 2114,
  [SMALL_STATE(93)] = 2124,
  [SMALL_STATE(94)] = 2138,
  [SMALL_STATE(95)] = 2152,
  [SMALL_STATE(96)] = 2166,
  [SMALL_STATE(97)] = 2180,
  [SMALL_STATE(98)] = 2194,
  [SMALL_STATE(99)] = 2208,
  [SMALL_STATE(100)] = 2222,
  [SMALL_STATE(101)] = 2236,
  [SMALL_STATE(102)] = 2250,
  [SMALL_STATE(103)] = 2264,
  [SMALL_STATE(104)] = 2274,
  [SMALL_STATE(105)] = 2288,
  [SMALL_STATE(106)] = 2302,
  [SMALL_STATE(107)] = 2314,
  [SMALL_STATE(108)] = 2324,
  [SMALL_STATE(109)] = 2335,
  [SMALL_STATE(110)] = 2346,
  [SMALL_STATE(111)] = 2355,
  [SMALL_STATE(112)] = 2364,
  [SMALL_STATE(113)] = 2375,
  [SMALL_STATE(114)] = 2386,
  [SMALL_STATE(115)] = 2395,
  [SMALL_STATE(116)] = 2406,
  [SMALL_STATE(117)] = 2415,
  [SMALL_STATE(118)] = 2424,
  [SMALL_STATE(119)] = 2435,
  [SMALL_STATE(120)] = 2444,
  [SMALL_STATE(121)] = 2455,
  [SMALL_STATE(122)] = 2466,
  [SMALL_STATE(123)] = 2477,
  [SMALL_STATE(124)] = 2488,
  [SMALL_STATE(125)] = 2499,
  [SMALL_STATE(126)] = 2510,
  [SMALL_STATE(127)] = 2521,
  [SMALL_STATE(128)] = 2532,
  [SMALL_STATE(129)] = 2543,
  [SMALL_STATE(130)] = 2554,
  [SMALL_STATE(131)] = 2565,
  [SMALL_STATE(132)] = 2576,
  [SMALL_STATE(133)] = 2587,
  [SMALL_STATE(134)] = 2598,
  [SMALL_STATE(135)] = 2609,
  [SMALL_STATE(136)] = 2620,
  [SMALL_STATE(137)] = 2631,
  [SMALL_STATE(138)] = 2642,
  [SMALL_STATE(139)] = 2651,
  [SMALL_STATE(140)] = 2662,
  [SMALL_STATE(141)] = 2670,
  [SMALL_STATE(142)] = 2678,
  [SMALL_STATE(143)] = 2686,
  [SMALL_STATE(144)] = 2694,
  [SMALL_STATE(145)] = 2702,
  [SMALL_STATE(146)] = 2710,
  [SMALL_STATE(147)] = 2718,
  [SMALL_STATE(148)] = 2726,
  [SMALL_STATE(149)] = 2734,
  [SMALL_STATE(150)] = 2742,
  [SMALL_STATE(151)] = 2750,
  [SMALL_STATE(152)] = 2758,
  [SMALL_STATE(153)] = 2766,
  [SMALL_STATE(154)] = 2774,
  [SMALL_STATE(155)] = 2782,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(155),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(150),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(155),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(150),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(132),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_body_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_body_repeat1, 2, 0, 0), SHIFT_REPEAT(152),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_body_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_body_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_modifiers, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_modifiers_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_modifiers_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_declaration, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_declaration, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_declaration, 5, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_declaration, 5, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_body, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_body, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_declaration, 5, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_declaration, 5, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_declaration, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_declaration, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 6, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 6, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_declaration, 6, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_declaration, 6, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_declaration, 6, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_declaration, 6, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_body, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_body, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 8, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 8, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 6, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 6, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_declaration, 4, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_declaration, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(154),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implements_clause, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_implements_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_implements_clause_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implements_clause, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_clause, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [350] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 2, 0, 0),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gosu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
